export const Jobs: {
  position: string;
  experience: string;
  location: string;
  jobDescription: string[];
  qualification: string[];
}[] = [
  {
    position: "Project Manager",
    experience: "8 - 10 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Oversee and manage multiple projects, ensuring timely delivery and quality standards.",
      "Develop and maintain project management frameworks, methodologies, and best practices.",
      "Coordinate between teams, stakeholders, and clients to ensure project alignment with business goals.",
      "Monitor project progress, budgets, risks, and resource allocation.",
      "Implement and optimize project tracking tools for efficiency and transparency.",
      "Facilitate meetings, prepare project reports, and ensure adherence to company policies and compliance standards.",
      "Identify and mitigate risks to ensure smooth project execution.",
      "Support strategic decision-making by analyzing project performance and providing insights.",
      "Promote a culture of continuous improvement and process optimization within the project management team.",
      "Ensure all documentation, reports, and records are accurately maintained.",
    ],
    qualification: [
      "Educational Background: Bachelor's or Master’s degree in Business Administration, Project Management, IT, or a related field.",
      "Certifications: PMP, PRINCE2, or Certified Scrum Master (preferred but not mandatory).",
      "Project Management Expertise: Strong knowledge of Agile, Scrum, Waterfall, and other project management methodologies.",
      "Experience: 2-5 years of project management experience, preferably in IT, software development, or corporate project management.",
      "Technical Proficiency: Experience with project management tools like Jira, Trello, Asana, or Microsoft Project.",
      "Leadership & Communication: Strong organizational, leadership, and problem-solving skills with excellent stakeholder management.",
      "Risk & Budget Management: Ability to manage budgets, allocate resources, and mitigate risks effectively.",
      "Analytical & Decision-Making Skills: Ability to analyze project performance and provide strategic recommendations.",
    ],
  },

  {
    position: "Business Development Manager",
    experience: "10+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "<b>Sales Strategy & Planning:</b> Develop and implement effective sales strategies to meet business objectives. Identify key growth areas, emerging markets, and potential clients. Focus on technology, marketplace, and segment growth strategies.",
      "<b>Lead Generation & Client Acquisition:</b> Generate leads, manage the sales pipeline, and convert prospects into long-term clients. To pitch IT solutions and services, and engage with decision-makers across industries such as BFSI, Manufacturing, Retail, Food Processing, and Pharma. Arrange and conduct business meetings with prospective clients.",
      "<b>Relationship Management:</b> Build and maintain strong, long-lasting client relationships by understanding their needs and providing tailored solutions. Provide trustworthy feedback and after-sales support to ensure client satisfaction.",
      "<b>Revenue Generation:</b> Achieve or exceed sales targets by promoting the company's IT services, including software development, website development, cloud services, ERP solutions, and other technology offerings. Drive sales through account mining and sales hunting strategies.",
      "<b>Market Research & Analysis:</b> Conduct thorough market analysis to identify new business opportunities, industry trends, and competitive activities. Adjust sales strategies based on insights from market research.",
      "<b>Team Collaboration:</b> Work closely with marketing, technical, pre-sales, and post-sales teams to ensure a seamless customer experience. Provide feedback and insights to product development teams based on client needs.",
      "<b>Reporting & Forecasting:</b> Provide regular sales forecasts and performance reports to the leadership team. Track sales metrics and adjust strategies as needed.",
      "<b>Networking & Industry Participation:</b> Represent the company at industry events, conferences, and forums to expand the company’s presence. Engage with potential clients on a global level.",
    ],
    qualification: [
      "Proven track record of 10+ years in business development, lead generation, or sales, with a strong focus on IT solutions and services.",
      "Experience in customer support and managing large, complex deals with long sales cycles.",
      "Strong understanding of IT services, including AI/ML, Salesforce, SAP, ERP solutions, and bespoke developments. Extensive network within the IT industry and experience engaging with CEOs, Owners, CXOs, IT Heads, and other decision-makers.",
      "Proficiency in MS Office and CRM software (e.g., Salesforce).",
      "Market knowledge of BFSI, Manufacturing, Retail, Food Processing, and Pharma industries with captive centers (GCC).",
      "Ability to self-hunt leads, plan strategies, and execute them in international sales markets.",
      "Proficiency in English, with additional foreign languages being an advantage.",
    ],
  },

  {
    position: "Senior Azure Data Engineer",
    experience: "8 - 10 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Design, develop, and maintain scalable and high-performance data pipelines using Azure Data Services (Azure Data Factory, Azure Databricks, Azure Synapse, etc.).",
      "Build and optimize data models, ETL/ELT processes, and data integration workflows.",
      "Implement best practices for data storage, transformation, and processing to support analytics and business intelligence needs.",
      "Develop and manage data lakes, data warehouses, and real-time streaming solutions on Azure.",
      "Collaborate with data analysts, data scientists, and software engineers to ensure seamless data integration and processing.",
      "Ensure data security, compliance, and governance in line with industry best practices and regulatory requirements.",
      "Monitor and troubleshoot data pipelines, optimizing performance and reliability.",
      "Automate data workflows and infrastructure using DevOps and CI/CD practices.",
      "Work with stakeholders to understand business requirements and translate them into effective data solutions.",
    ],
    qualification: [
      "8 to 10 years of experience in data engineering, with at least 3+ years working with Azure data services.",
      "Strong expertise in Azure Data Factory (ADF), Azure Synapse Analytics, Azure Databricks, Azure Data Lake, and Azure SQL Database.",
      "Proficiency in SQL, Python, or Scala for data processing and transformation.",
      "Experience with Big Data technologies such as Spark, Delta Lake, and Parquet.",
      "Hands-on experience with ETL/ELT development and data pipeline orchestration.",
      "Knowledge of Azure DevOps, CI/CD, and Infrastructure as Code (Terraform, ARM templates, Bicep, etc.).",
      "Familiarity with data governance, security best practices, and compliance frameworks.",
      "Experience working with Power BI, Snowflake, or other BI/analytics tools is a plus.",
    ],
  },

  {
    position: "Senior AWS Data Engineer",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Design, develop, and optimize scalable data pipelines and ETL workflows using AWS services (Glue, Lambda, Step Functions, etc.).",
      "Implement and maintain data lakes and data warehouses on AWS (S3, Redshift, Athena, etc.).",
      "Develop and manage real-time and batch data processing solutions.",
      "Ensure data security, governance, and compliance with industry best practices.",
      "Collaborate with data scientists, analysts, and business teams to deliver data-driven solutions.",
      "Optimize query performance and troubleshoot data-related issues.",
      "Automate infrastructure deployment using IaC tools like Terraform or CloudFormation.",
      "Implement monitoring, logging, and alerting for data pipelines using AWS CloudWatch, Prometheus, etc.",
      "Mentor junior engineers and contribute to best practices in data engineering.",
    ],
    qualification: [
      "5+ years of experience in data engineering, with at least 3 years focused on AWS cloud services.",
      "Strong proficiency in AWS services like Glue, Redshift, S3, Lambda, EMR, and Athena.",
      "Expertise in SQL, Python, and Spark for data processing and analytics.",
      "Experience with ETL/ELT design and implementation.",
      "Familiarity with DevOps, CI/CD, and automation tools like Terraform, CloudFormation, and Jenkins.",
      "Strong understanding of data governance, security, and compliance best practices.",
      "Experience with real-time data processing using Kafka, Kinesis, or similar tools.",
      "Knowledge of database optimization, indexing, and partitioning techniques.",
    ],
  },

  {
    position: "Java Developer",
    experience: "5 - 7 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop, test, and maintain high-quality Java applications.",
      "Collaborate with cross-functional teams to design, develop, and deploy software solutions.",
      "Write clean, efficient, and scalable code following best practices.",
      "Troubleshoot and debug applications to optimize performance.",
      "Implement security and data protection solutions.",
      "Work with databases, including SQL and NoSQL, for data storage and retrieval.",
      "Maintain clear and concise technical documentation.",
      "Stay updated with the latest industry trends, tools, and technologies in Java development.",
    ],
    qualification: [
      "Bachelor's or Master's degree in Computer Science, Engineering, or a related field.",
      "5-7 years of hands-on experience in Java development.",
      "Proficiency in Core Java, Spring Boot, Hibernate, REST APIs, and Microservices architecture.",
      "Experience with frontend technologies like React, Angular, or Vue.js (optional but preferred).",
      "Strong knowledge of SQL and NoSQL databases (MySQL, PostgreSQL, MongoDB, etc.).",
      "Familiarity with CI/CD pipelines, Git, and version control systems.",
      "Knowledge of cloud platforms like AWS, Azure, or Google Cloud.",
      "Experience with Docker and Kubernetes is a plus.",
      "Strong problem-solving skills and the ability to work in a fast-paced environment.",
    ],
  },

  {
    position: "Java Full Stack Developer",
    experience: "3 - 8 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop and maintain scalable web applications using Java, Spring Boot, and Angular/React.",
      "Work with databases like MySQL, PostgreSQL, or MongoDB for efficient data storage and retrieval.",
      "Implement front-end UI/UX designs using HTML, CSS, JavaScript, and frameworks like Angular or React.",
      "Ensure application security, authentication, and authorization (OAuth, JWT, Spring Security).",
      "Optimize applications for speed, scalability, and performance.",
      "Write clean, reusable, and efficient code following best practices.",
      "Conduct unit testing and integration testing using JUnit, Mockito, or similar tools.",
      "Collaborate with cross-functional teams, including UI/UX designers, product managers, and DevOps engineers.",
      "Deploy applications on cloud platforms (AWS, Azure, or Google Cloud).",
      "Troubleshoot, debug, and upgrade applications as needed.",
      "Stay updated with the latest Java and full-stack development trends.",
      "Design, develop, and optimize RESTful APIs and microservices.",
    ],
    qualification: [
      "3-8 years of experience in Java Full Stack Developement",
      "Backend: Java, Spring Boot, Hibernate, Microservices.",
      "Frontend: Angular/React, JavaScript, TypeScript, HTML, CSS.",
      "Databases: MySQL, PostgreSQL, MongoDB.",
      "DevOps & Cloud: Docker, Kubernetes, AWS, Azure, CI/CD pipelines.",
      "Testing: JUnit, Mockito, Cypress, Selenium.",
      "Version Control: Git, GitHub, GitLab, Bitbucket.",
      "Security: OAuth, JWT, Spring Security.",
      "Strong analytical and problem-solving skills.",
      "Effective communication and teamwork abilities.",
      "Ability to work in an Agile/Scrum environment.",
      "Self-motivated and eager to learn new technologies.",
    ],
  },

  {
    position: "Digital Marketing Executive",
    experience: "3 - 6 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop, implement, and manage digital marketing campaigns across various channels (SEO, SEM, social media, email, etc.).",
      "Create engaging content for social media platforms, websites, and digital ads.",
      "Optimize website content and landing pages for SEO to improve search rankings.",
      "Monitor and analyze campaign performance using analytics tools and generate reports.",
      "Manage and grow social media presence across platforms like Facebook, Instagram, LinkedIn, and Twitter.",
      "Run paid ad campaigns (Google Ads, Facebook Ads, etc.) to drive traffic and conversions.",
      "Conduct market research and competitor analysis to identify trends and insights.",
      "Collaborate with designers, developers, and content creators to execute marketing strategies.",
      "Manage email marketing campaigns and optimize for engagement and lead generation.",
      "Stay updated with the latest digital marketing trends and best practices.",
    ],
    qualification: [
      "Bachelor’s degree in Marketing, Digital Marketing, Business, or a related field.",
      "3 - 6 years in digital marketing or related roles.",
      "Proficiency in SEO, Google Analytics, and Google Ads.",
      "Strong knowledge of social media platforms and advertising strategies.",
      "Experience with content marketing and email marketing tools.",
      "Basic knowledge of HTML, CSS, and website management is a plus.",
      "Excellent communication and analytical skills.",
      "Ability to work independently and in a team environment.",
    ],
  },

  {
    position: "Web Developer",
    experience: "3+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop, test, and maintain responsive web applications using modern front-end and back-end technologies.",
      "Collaborate with designers, product managers, and developers to create seamless user experiences.",
      "Write clean, maintainable, and efficient code following best practices.",
      "Optimize web applications for maximum speed and scalability.",
      "Integrate RESTful APIs and third-party services to enhance functionality.",
      "Troubleshoot and resolve technical issues, ensuring high performance and security.",
      "Stay updated with emerging web technologies and industry trends.",
      "Work with version control systems like Git for efficient code management.",
      "Ensure cross-browser and cross-device compatibility.",
      "Participate in code reviews and contribute to team knowledge sharing.",
    ],
    qualification: [
      "3+ years of experience in web development with expertise in modern frameworks and technologies.",
      "Proficiency in Front-end Technologies – HTML, CSS, JavaScript, React.js, Next.js",
      "Back-end Development – Node.js, Express.js",
      "Database Management – MongoDB, MySQL, or PostgreSQL",
      "Version Control – Git, GitHub/GitLab",
      "UI/UX Understanding – Knowledge of responsive design and accessibility",
      "State Management – Redux, Context API",
      "API Integration – RESTful APIs, third-party APIs",
      "Performance Optimization – Web performance best practices",
      "Problem-solving & Debugging – Ability to troubleshoot issues efficiently",
      "Education – Bachelor’s degree in Computer Science, IT, or a related field",
    ],
  },

  {
    position: "Graphics Designer",
    experience: "2 - 7 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop visually appealing designs for digital and print media, including websites, social media, advertisements, brochures, and branding materials.",
      "Collaborate with marketing, UI/UX, and development teams to create engaging graphics aligned with brand guidelines.",
      "Design compelling logos, illustrations, icons, and other visual elements.",
      "Enhance user experience by applying creative design principles to website and app interfaces.",
      "Use industry-standard software to create and edit images, layouts, and animations.",
      "Stay updated with design trends, tools, and techniques to bring innovative ideas.",
      "Optimize graphics for different screen sizes and devices while maintaining high quality.",
      "Ensure consistency in brand identity across all visual assets.",
      "Work on multiple projects simultaneously and meet tight deadlines.",
      "Provide creative input and suggest improvements for better visual storytelling.",
    ],
    qualification: [
      "2-7 years of experience in graphic design or a related field.",
      "Software Skills: Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign, After Effects), Figma, or other design tools.",
      "UI/UX Knowledge: Understanding of design principles, typography, color theory, and layout techniques.",
      "Creativity & Innovation: Strong ability to conceptualize and execute original design ideas.",
      "Communication & Collaboration: Ability to work with cross-functional teams and articulate design ideas effectively.",
      "Attention to Detail: Strong eye for detail to ensure pixel-perfect designs.",
      "Motion Graphics & Video Editing (Optional): Knowledge of basic animation and video editing is a plus.",
    ],
  },

  {
    position: "Salesforce Developer",
    experience: "2 - 5 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Design, develop, test, and deploy customized Salesforce solutions to meet business requirements.",
      "Develop and maintain Salesforce applications using Apex, Visualforce, Lightning Components (Aura & LWC), and Salesforce APIs.",
      "Customize and configure Salesforce objects, fields, workflows, process builder, and validation rules.",
      "Integrate Salesforce with third-party applications and services using REST/SOAP APIs.",
      "Implement automation solutions using Salesforce Flows and Triggers.",
      "Optimize and improve existing Salesforce applications for performance and scalability.",
      "Collaborate with stakeholders, business analysts, and cross-functional teams to understand and implement business needs.",
      "Ensure security, compliance, and best practices within the Salesforce platform.",
      "Troubleshoot and resolve technical issues in Salesforce applications.",
      "Stay updated with Salesforce releases, new features, and best practices.",
    ],
    qualification: [
      "2-5 years of Salesforce development experience.",
      "Proficiency in Apex, Visualforce, Lightning Web Components (LWC), and Aura Components.",
      "Strong knowledge of Salesforce Object Model, SOQL, SOSL, and Governor Limits.",
      "Experience with Salesforce automation tools (Workflows, Process Builder, Flow, Approval Processes).",
      "Hands-on experience in Salesforce integration (REST/SOAP APIs, Web Services, Middleware like Mulesoft, etc.).",
      "Understanding of Salesforce security models (Profiles, Permission Sets, Sharing Rules).",
      "Experience with CI/CD, Version Control (Git, Bitbucket, Jenkins, etc.) for Salesforce development.",
      "Knowledge of Agile methodologies and tools like Jira or Trello.",
      "Salesforce Developer Certification (PD1, PD2) is a plus.",
      "Strong problem-solving, analytical, and communication skills.",
    ],
  },

  {
    position: "IT Recruiter",
    experience: "2 - 5 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Identify and source top IT talent through various channels (job portals, social media, referrals, networking).",
      "Screen resumes, conduct initial interviews, and evaluate candidates based on technical and cultural fit.",
      "Coordinate and schedule interviews between candidates and hiring managers.",
      "Build and maintain a strong pipeline of qualified candidates for current and future job openings.",
      "Manage the end-to-end recruitment process, from sourcing to onboarding.",
      "Collaborate with hiring managers to understand job requirements and develop effective hiring strategies.",
      "Utilize ATS (Applicant Tracking System) and other recruitment tools to streamline hiring processes.",
      "Stay updated with the latest trends in IT recruitment and hiring practices.",
      "Develop relationships with candidates and provide a positive candidate experience.",
      "Negotiate salary and employment terms with selected candidates.",
    ],
    qualification: [
      "2-5 years of experience in IT recruitment, talent acquisition, or HR",
      "Strong understanding of IT job roles, technologies, and industry trends.",
      "Hands-on experience with job portals (LinkedIn, Naukri, Indeed, etc.).",
      "Excellent communication and interpersonal skills.",
      "Proficiency in ATS and recruitment software.",
      "Ability to multitask and work in a fast-paced environment.",
      "Strong negotiation and decision-making skills.",
      "Knowledge of employment laws and hiring best practices.",
      "Ability to build and maintain strong candidate relationships.",
    ],
  },

  {
    position: "Business Development Executive",
    experience: "3 - 5 years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Identify and generate new business opportunities through market research and networking.",
      "Develop and maintain strong relationships with potential and existing clients.",
      "Understand client needs and offer tailored IT solutions.",
      "Conduct sales presentations, product demonstrations, and negotiations.",
      "Collaborate with the marketing team for lead generation and brand awareness.",
      "Achieve sales targets and contribute to business growth.",
      "Maintain accurate records of sales activities and client interactions in CRM tools.",
      "Stay updated on industry trends, market conditions, and competitor activities.",
    ],
    qualification: [
      "0 - 2 years of experience in business development, sales, or a related field.",
      "Ability to understand IT products and services to effectively pitch solutions.",
      "Strong communication, negotiation, and interpersonal skills.",
      "Self-motivated, goal-oriented, and capable of working independently.",
      "Basic knowledge of CRM tools and MS Office Suite.",
      "Strong analytical and problem-solving skills.",
      "Ability to adapt and thrive in a fast-paced business environment.",
    ],
  },

  {
    position: "Python Developer",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop, test, and maintain scalable and efficient Python-based applications.",
      "Design and implement robust APIs and backend services using Django, Flask, or FastAPI.",
      "Collaborate with front-end developers, designers, and stakeholders to deliver high-quality solutions.",
      "Optimize application performance and ensure high availability and scalability.",
      "Write clean, maintainable, and well-documented code following best practices.",
      "Debug and troubleshoot issues, ensuring seamless application functionality.",
      "Work with databases like PostgreSQL, MySQL, or MongoDB to manage data efficiently.",
      "Integrate third-party services, APIs, and cloud solutions.",
      "Ensure application security and implement authentication and authorization mechanisms.",
      "Participate in code reviews, mentoring junior developers, and continuous learning.",
    ],
    qualification: [
      "Proficient in Python with hands-on experience in Django, Flask, or FastAPI.",
      "Strong understanding of SQL (PostgreSQL, MySQL) and NoSQL (MongoDB, Redis)",
      "Knowledge of RESTful APIs, authentication, and web services.",
      "Experience with AWS, Azure, or Google Cloud for deployment and server management.",
      "Proficiency in Git and CI/CD pipelines.",
      "Strong debugging and unit testing skills using PyTest or Unittest.",
      "Experience with Pandas, NumPy, and data processing frameworks.",
      "Familiarity with OWASP principles and API security.",
      "Minimum 5+ years in Python development with proven project experience.",
    ],
  },

  {
    position: "Front-End Developer",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop, optimize, and maintain responsive web applications with a focus on user experience.",
      "Collaborate with UX/UI designers, back-end developers, and product teams to deliver seamless interfaces.",
      "Write clean, maintainable, and efficient code using modern front-end technologies.",
      "Ensure cross-browser compatibility, performance optimization, and accessibility best practices.",
      "Implement and maintain state management using Redux, Context API, or similar tools.",
      "Work with RESTful APIs, GraphQL, and third-party integrations for dynamic web applications.",
      "Stay up-to-date with the latest front-end trends and frameworks to enhance development efficiency.",
      "Participate in code reviews, debugging, and troubleshooting to improve application stability.",
      "Optimize applications for maximum speed and scalability.",
    ],
    qualification: [
      "5+ years of professional front-end development experience.",
      "Proficiency in React.js, Next.js, JavaScript (ES6+), TypeScript.",
      "Strong understanding of HTML5, CSS3, Tailwind CSS, Bootstrap, and Sass.",
      "Experience with Redux, Context API, Zustand, or similar state management libraries.",
      "Hands-on experience in RESTful APIs, GraphQL, and WebSockets.",
      "Knowledge of performance optimization techniques and accessibility standards.",
      "Familiarity with testing frameworks like Jest, Cypress, or React Testing Library.",
      "Experience with build tools (Webpack, Vite) and package managers (NPM, Yarn).",
      "Version control using Git, GitHub, GitLab, or Bitbucket.",
      "Exposure to Agile methodologies and CI/CD pipelines.",
    ],
  },

  {
    position: "Data Scientist",
    experience: "7+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop and implement machine learning models, predictive analytics, and AI-driven solutions to solve complex business problems.",
      "Design, build, and maintain scalable data pipelines and architectures for data ingestion, processing, and visualization.",
      "Conduct statistical analysis, hypothesis testing, and A/B testing to drive data-driven decision-making.",
      "Collaborate with cross-functional teams, including engineers, product managers, and business analysts, to integrate data science solutions.",
      "Optimize and enhance data models, algorithms, and AI frameworks for improved efficiency and accuracy.",
      "Interpret and communicate insights from large, complex datasets to stakeholders using data visualization tools.",
      "Ensure data quality, integrity, and governance while adhering to compliance and security standards.",
      "Stay updated with emerging trends, technologies, and best practices in data science, AI, and big data analytics.",
    ],
    qualification: [
      "7+ years of experience in data science, machine learning, or AI-driven solutions.",
      "Strong programming skills in Python, R, or Scala.",
      "Expertise in machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn.",
      "Experience with big data technologies like Hadoop, Spark, or Databricks.",
      "Proficiency in SQL and NoSQL databases for data extraction and manipulation.",
      "Knowledge of cloud platforms such as AWS, Azure, or Google Cloud for deploying ML models.",
      "Experience in deep learning, NLP, time-series forecasting, and recommendation systems.",
      "Familiarity with DevOps/MLOps practices for model deployment and monitoring.",
      "Strong understanding of statistical modeling, probability, and mathematical optimization.",
    ],
  },

  {
    position: "Software Test Engineer",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Design, develop, and execute automated and manual test cases to ensure software quality.",
      "Perform functional, regression, integration, performance, and security testing.",
      "Collaborate with developers, product managers, and other stakeholders to define test strategies and improve software quality.",
      "Identify, document, and track bugs using defect tracking tools like JIRA, Bugzilla, or similar.",
      "Develop and maintain test automation frameworks using Selenium, Cypress, Playwright, or similar tools.",
      "Ensure software meets industry standards and best practices in testing methodologies.",
      "Participate in code reviews, sprint planning, and agile development processes.",
      "Analyze test results, generate test reports, and suggest improvements for continuous integration and deployment.",
      "Work closely with DevOps teams to implement CI/CD pipelines and optimize testing environments.",
    ],
    qualification: [
      "5+ years of experience in software testing and quality assurance.",
      "Strong experience with automation tools (Selenium, Cypress, Playwright, Appium, etc.).",
      "Proficiency in scripting languages like Java, Python, JavaScript, or C#.",
      "Hands-on experience with API testing tools like Postman, RestAssured, or SoapUI.",
      "Knowledge of performance testing tools like JMeter or LoadRunner.",
      "Experience with CI/CD tools such as Jenkins, GitHub Actions, GitLab CI/CD.",
      "Strong understanding of testing methodologies, SDLC, STLC, and Agile practices.",
      "Experience with databases and writing SQL queries for data validation.",
      "Familiarity with cloud platforms like AWS, Azure, or Google Cloud.",
      "Excellent analytical, problem-solving, and debugging skills.",
      "Strong communication and teamwork abilities.",
    ],
  },

  {
    position: "HR Manager",
    experience: "8+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop and implement HR strategies aligned with business goals.",
      "Oversee recruitment, onboarding, and talent acquisition processes.",
      "Manage employee relations, address grievances, and foster a positive workplace culture.",
      "Develop and enforce company policies, ensuring compliance with labor laws.",
      "Design and implement performance management systems and training programs.",
      "Handle payroll, benefits administration, and compensation structures.",
      "Collaborate with department heads to improve workforce productivity and engagement.",
      "Drive diversity, equity, and inclusion initiatives.",
      "Monitor HR metrics and prepare reports for senior management.",
      "Implement HR technology solutions to streamline operations.",
    ],
    qualification: [
      "8+ years of progressive HR experience, with at least 3 years in a managerial role.",
      "Strong knowledge of labor laws, HR best practices, and compliance regulations.",
      "Excellent leadership, decision-making, and conflict-resolution skills.",
      "Proficiency in HR software and applicant tracking systems (ATS).",
      "Exceptional communication and interpersonal skills.",
      "Ability to manage multiple tasks in a fast-paced environment.",
      "Experience in organizational development and strategic HR planning.",
    ],
  },

  {
    position: "Account Manager",
    experience: "10+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop and maintain strong relationships with key clients, ensuring long-term business growth.",
      "Act as the primary point of contact for client accounts, addressing needs and providing tailored solutions.",
      "Collaborate with internal teams to align business strategies with client objectives.",
      "Monitor and analyze key account metrics, ensuring optimal performance and customer satisfaction.",
      "Drive revenue growth by identifying new opportunities within existing accounts.",
      "Negotiate contracts, pricing, and service agreements to maximize profitability.",
      "Stay updated on industry trends and market developments to provide insights and recommendations.",
      "Ensure seamless communication between clients and internal teams for efficient project execution.",
      "Develop reports and presentations for senior management, outlining key account performance.",
      "Handle escalations and resolve client issues proactively to maintain strong relationships.",
    ],
    qualification: [
      "10+ years of experience in account management, client relations, or sales.",
      "Proven ability to manage multiple client accounts and drive revenue growth.",
      "Strong negotiation, communication, and interpersonal skills.",
      "Experience in developing and executing strategic account plans.",
      "Proficiency in CRM tools (Salesforce, HubSpot, or similar).",
      "Ability to analyze data and generate insights for business development.",
      "Leadership skills with experience in mentoring or leading a team.",
      "Problem-solving mindset with a client-focused approach.",
    ],
  },

  {
    position: "Business Client Delivery",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Manage and oversee client delivery processes, ensuring seamless execution of business solutions.",
      "Develop and maintain strong relationships with clients to understand their needs and provide tailored solutions.",
      "Coordinate with internal teams to ensure projects are delivered on time, within scope, and meet quality standards.",
      "Act as a point of contact for clients, addressing concerns and resolving issues efficiently.",
      "Analyze business requirements and work collaboratively with stakeholders to optimize service delivery.",
      "Identify opportunities for process improvements and implement best practices to enhance client satisfaction.",
      "Ensure compliance with company policies, industry standards, and regulatory requirements.",
      "Monitor key performance indicators (KPIs) to track project success and client satisfaction.",
      "Lead and mentor junior team members, fostering a culture of growth and excellence.",
    ],
    qualification: [
      "5+ years of experience in business client delivery, project management, or customer success.",
      "Strong project management and organizational skills.",
      "Excellent communication and stakeholder management.",
      "Ability to analyze business requirements and develop effective solutions.",
      "Problem-solving and decision-making capabilities.",
      "Proficiency in CRM tools and business intelligence software.",
      "Knowledge of industry best practices and client service strategies.",
      "Team leadership and mentoring experience.",
    ],
  },

  {
    position: "Business Analyst",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Analyze business requirements and translate them into functional specifications.",
      "Work closely with stakeholders to identify business needs and propose solutions.",
      "Develop and document business processes, workflows, and data models.",
      "Collaborate with development teams to ensure successful implementation of business solutions.",
      "Conduct gap analysis and recommend process improvements.",
      "Assist in user acceptance testing (UAT) and quality assurance processes.",
      "Monitor project progress and provide reports to management.",
      "Facilitate meetings, gather feedback, and ensure alignment between business goals and technical execution.",
      "Prepare and maintain comprehensive documentation for future reference.",
      "Stay updated with industry trends and best practices to enhance business analysis methodologies.",
    ],
    qualification: [
      "5+ years of experience in business analysis, process improvement, or related roles",
      "Proficiency in business analysis tools (e.g., JIRA, Confluence, Microsoft Visio, Lucidchart).",
      "Strong knowledge of SQL for data analysis.",
      "Experience with Agile and Scrum methodologies.",
      "Understanding of software development life cycle (SDLC).",
      "Excellent communication and stakeholder management skills.",
      "Strong problem-solving and analytical thinking abilities.",
      "Ability to work in a fast-paced, collaborative environment.",
    ],
  },

  {
    position: "Research Analyst",
    experience: "2+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Conduct in-depth research on industry trends, market conditions, and competitors.",
      "Collect, analyze, and interpret qualitative and quantitative data to generate insights.",
      "Prepare detailed reports, presentations, and visualizations to support decision-making.",
      "Work with cross-functional teams to provide data-driven recommendations.",
      "Stay updated with the latest research methodologies and analytical tools.",
      "Identify new opportunities and potential risks through data analysis.",
      "Ensure data accuracy, integrity, and compliance with research standards.",
      "Present findings to stakeholders and assist in strategic planning.",
    ],
    qualification: [
      "Proficiency in data analysis tools (Excel, SQL, Python, R, or similar).",
      "Experience with market research techniques and statistical analysis.",
      "Knowledge of data visualization tools (Power BI, Tableau, or similar).",
      "Strong understanding of research methodologies and data interpretation.",
      "Excellent analytical and problem-solving skills.",
      "Strong communication and presentation abilities.",
      "Attention to detail and critical thinking.",
      "Ability to work independently and in a team environment.",
    ],
  },

  {
    position: "Digital Marketing Expert",
    experience: "5+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Develop, implement, and manage digital marketing campaigns across various channels (SEO, SEM, PPC, social media, email marketing, and content marketing).",
      "Conduct market research to identify trends, customer insights, and competitive strategies.",
      "Optimize website and l,anding pages for better user experience, conversion rates, and search engine rankings (SEO & CRO).",
      "Plan and ex,ecute paid advertising campaigns on Google Ads, Facebook Ads, LinkedIn Ads, and other platforms.",
      "Monitor, analyze, and r,eport performance metrics (Google Analytics, Search Console, and other tracking tools) to improve ROI.",
      "Develop content strategies to enhance brand awareness and engagement.",
      "Manage social media a,ccounts, create engaging posts, and interact with the audience to grow followers and increase engagement.",
      "Stay updated with the latest digital marketing trends, tools, and algorithm updates.",
      "Collaborate with the design, content, and development teams to create impactful marketing strategies.",
      "Manage email marketing campaigns, automation, and customer segmentation for better engagement.",
    ],
    qualification: [
      "5+ years of experience in digital marketing, performance marketing, and social media management.",
      "Expertise in SEO, SEM, PPC, and Google Ads for campaign optimization.",
      "Strong understanding of Google Analytics, Google Search Console, and Facebook Business Manager for data-driven decision-making.",
      "Experience with marketing automation tools like HubSpot, Mailchimp, or ActiveCampaign.",
      "Proficiency in content marketing and social media strategies (LinkedIn, Instagram, Facebook, Twitter, etc.).",
      "Strong knowledge of A/B testing, conversion rate optimization (CRO), and lead generation.",
      "Hands-on experience in keyword research, backlink strategies, and technical SEO.",
      "Basic knowledge of HTML, CSS, and website CMS (WordPress, Shopify, etc.) is a plus.",
      "Excellent analytical, problem-solving, and communication skills.",
    ],
  },

  {
    position: "Content Writer",
    experience: "3+ years",
    location: "Kharadi, Pune",
    jobDescription: [
      "Create high-quality, engaging, and SEO-optimized content for websites, blogs, social media, and marketing materials.",
      "Research industry-related topics to generate innovative content ideas that align with business goals.",
      "Develop compelling and persuasive copy for landing pages, product descriptions, email campaigns, and advertisements.",
      "Collaborate with designers, marketers, and developers to enhance content with visuals, infographics, and multimedia elements.",
      "Edit and proofread content to ensure clarity, consistency, and adherence to brand voice and tone.",
      "Optimize content for search engines (SEO) using keyword research and best practices.",
      "Stay updated with industry trends, content marketing strategies, and digital marketing best practices.",
      "Manage multiple content projects while meeting deadlines and maintaining quality standards.",
    ],
    qualification: [
      "Minimum 3+ years of professional content writing experience.",
      "Strong writing, editing, and proofreading skills with excellent grammar and vocabulary.",
      "Ability to create engaging, informative, and conversion-driven content.",
      "Proficiency in SEO best practices, keyword research, and on-page optimization.",
      "Experience with content management systems (CMS) like WordPress.",
      "Familiarity with digital marketing concepts, including social media and email marketing.",
      "Creativity, adaptability, and strong research skills.",
      "Knowledge of analytics tools like Google Analytics is a plus.",
      "Ability to work independently and collaborate effectively with cross-functional teams.",
    ],
  },
];
